package com.concerto.sprinklr.application.init;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class AppConstants {
	public static final String APPLICATION_LOGGER = "AppLogger";
	static Logger logger = LoggerFactory.getLogger("AppLogger");
	public static final String CONFIG_PROPERTIES_FILE = "config.properties";
	public static final String CONN_USERNAME = "1database.connection.username";
	public static final String CONN_IMP = "database.connection.password";
	public static final String CONN_URL = "database.connection.url";
	public static final String CONN_DRIVER = "database.connection.driver";
	public static final String PARALLEL_REQUEST_PROCESSING_COUNT = "parallel.request.processing.count";
	public static final String POLLING_PROCEDURE_NAME = "polling.procedure.name";
	public static final String UPDATE_STATUS_PROCEDURE_NAME = "update.status.procedure.name";
	public static final String UPDATE_PENDING_PROCEDURE_NAME = "update.pending.procedure.name";
	public static final String REQUEST_URL = "request.url";
	public static final String DATABASE_DATE_FORMAT = "database.date.format";
	public static final String REQUEST_PROCESSING_METHOD = "request.processing.method";
	public static final String REQUEST_HEADERS = "request.header";
	public static final String HEADER_SEPARATOR = "header.separator";
	public static final String REQ_SORT_ENABLE = "req.sorting.enable";
	public static final String REQ_SORT_TYPE = "req.sorting.type";
	public static final String HTTP_REQUEST_METHOD = "http.request.method";
	public static final String REQUEST_POLLING_INTERVAL = "request.polling.interval";
	public static final String REQUEST_PROCESSING_INTERVAL = "request.processing.interval";
	public static final String CONNECTION_TIMEOUT = "connection.timeout";
	public static final String READ_TIMEOUT = "read.timeout";
	public static final String FILE_WATCHING_INTERVAL = "file.watching.interval";
	public static final String CERTIFICATE_BYPASS_ENABLE = "certificate.bypass.enable";
	public static final String REQ_LOG_MASKING_ENABLE = "req.log.masking.enable";
	public static final String RES_LOG_MASKING_ENABLE = "res.log.masking.enable";
	public static final String MASKING_CHARACTAR = "Masking.character";
	public static final String REQUEST_SENSITIVE_FIELDS = "request.sensitive.fields";
	public static final String RESPONSE_SENSITIVE_FIELDS = "response.sensitive.fields";
	public static final String SENSITIVE_FIELD_SEPARATOR = "field.separator";
	public static final String INITIAL_POOL_SIZE = "InitialPoolSize";
	public static final String MIN_POOL_SIZE = "MinPoolSize";
	public static final String MAX_POOL_SIZE = "MaxPoolSize";
	public static final String VALIDATE_CONN_ON_BORROW = "Validate.connection.on.borrow";
	public static final String SEC_TO_TRUST_IDLE_CONN = "Seconds.to.trust.idle.conn";
	public static final String DB_POOL_NAME = "dbPoolName";
	public static final String LOG4J_CONFIG_KEY = "log4j2.config.key";
	public static final String JOURNEY_ID = "journeyId";
	public static final String CHANNEL_TYPE = "channelType";
	public static final String FIRST_NAME = "firstName";
	public static final String NAME = "name";
	public static final String AUTHORIZATION = "Authorization";
	public static final String AUTHORIZATION_VALUE = "Authorization.value";
	public static final String KEY = "key";
	public static final String KEY_VALUE = "key_value";
	public static final String CONTENT_TYPE = "contenttype";
	public static final String CONTENT_TYPE_VALUE = "contenttype.value";
	public static final String BANK_CODE = "bankCode";
	public static final String CHANNEL = "channel";
	public static final String USERID = "userId";
	public static final String TRANSACTION_BRANCH = "transactionBranch";
	public static final String TRANSACTION_PARTY_CODE = "transactingPartyCode";
	public static final String MAX_RANDOM_NUMBER = "max.random.number";
	public static final String IGNORE_DEDUP = "ignore.dedup";
	public static final String HTTP_OK_MESSAGE_TYPE = "200";
	public static final String REQUEST_POLLING_THREAD = "RequestPollingThread";
	public static final String MULTI_PROCESSING_THREAD = "MultiProcessingThread";
	public static final String FILE_WATCHING_THREAD = "FileWatchingThread";
	public static final String CONNECTION_FACTORY_CLASS_NAME = "oracle.jdbc.pool.OracleDataSource";
	public static final String HTTP_REQUESTER = "HTTP_REQUESTER";
	public static final String REST_REQUESTER = "REST_REQUESTER";
	public static final String HTTP = "http://";
	public static final String HTTPS = "https://";
	public static final String PBKDF2WITHHMACSHA512 = "PBKDF2WithHmacSHA512";
	public static final String AES = "AES";
	public static final String PKCS5PADDING = "PKCS5Padding";
	public static final String SEP = "/";
	public static final String ECB = "ECB";
	public static final int ONE = 1;
	public static final String INPUT_VLDTN_1 = "\n";
	public static final String INPUT_VLDTN_2 = "\r";
	public static final String INPUT_VLDTN_3 = "..\\";
	public static final String INPUT_VLDTN_4 = "../";
	public static final String INPUT_VLDTN_5 = "";
	public static final String comma = ",";
	public static final String bracket1 = "[";
	public static final String bracket2 = "]";
	public static final String MOBILE_NO_NOT_PRESENT = "[*MOBILE NO. NOT PRESENT CANNOT SEND TO SPRINKLR*]";
	public static final String INVALID_MOBILE_NUMBER = "[*INVALID MOBILE NUMBER CANNOT SEND TO SPRINKLR*]";
	public static final int Mob_Length = 10;
	public static final String SUCCESS = "SUCCESS";

	public AppConstants() {
	}
}
